---
- name: Webserver Setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

- name: Databse Setup
  hosts: dbervers
  become: yes
  tasks:
    - name: Install Mariadb
      ansible.builtin.yum:
        name: mariadb-server
        state: present