---
- name: Webserver Setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and Enabled httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

- name: Database Setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Start and Enabled mariadb-server
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes