---
- name: Database Setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Install PyMySQL client library
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start and Enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'accounts'
      community.mysql.mysql_db:
        name: accounts
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create database user with name 'bob' and password 'admin943' with all database privileges
      community.mysql.mysql_user:
        name: bob
        password: 'admin943'
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock