---
- name: Database Setup
  hosts: dbserver
  become: yes
  # vars:
  #   dbname: electric
  #   dbuser: current
  #   dbpass: tesla
  tasks:
    - debug:
        msg: "The dbname is {{dbname}}"
    - debug:
        var: dbuser
    - name: Install mariadb
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Install PyMySQL client library
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start and Enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create database 
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock